### ISSUE TITLE
The adafruit library folder seems to be empty

### ISSUE THREAD

**Issue by lifthoofd** [WorldWilderLab/Planet#12]

**Comment by ghost** [comment]
I added to the adafruit library - I don't think it will build with the
default one. Not sure why it isn't up there but will check.

**Comment by lifthoofd** [comment]
i have put the library back that you once mailed to me with all the other
files so it shouldnt be the default one, but please check if that is the
case

On Sat, Mar 14, 2015 at 1:55 AM, artag notifications@github.com wrote:

> I added to the adafruit library - I don't think it will build with the
> default one. Not sure why it isn't up there but will check.
> 
> On Fri, Mar 13, 2015 at 3:34 PM, Erik notifications@github.com wrote:
> 
> > Closed #12 https://github.com/WorldWilderLab/OrganicCinema/issues/12.
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/WorldWilderLab/OrganicCinema/issues/12#event-252070362>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/WorldWilderLab/OrganicCinema/issues/12#issuecomment-79611689
> .

## 

tel: +31624144454
web: http://www.lifthoofd.nl
email: eovermeire@gmail.com
